
server:
  port: 8080

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  application:
    name: PROXY-CLIENT
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
            loggerLevel: FULL
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: false
      eager-load:
        enabled: true
        clients:
          - USER-SERVICE
          - PRODUCT-SERVICE
          - ORDER-SERVICE
          - PAYMENT-SERVICE
          - SHIPPING-SERVICE
          - FAVOURITE-SERVICE

resilience4j:
  circuitbreaker:
    instances:
      proxyService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: false

logging:
  level:
    feign: DEBUG
    com.selimhorri.app.business.product.service: DEBUG

